name: 🚀 Deploy to Azure App Service
on: push
env:
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }}
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      - name: 🛠 Build Jar
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar
          mv ./build/libs/meal-viewer* app.jar
      - name: 🚀 Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: meal-viewer
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./app.jar